#ifndef USAGE_H
#define USAGE_H


#define LOADING_CALIBRATION_PARAMETERS 20
#define FINDING_ARUCO_MARKERS 21
#define CHESSBOARD_IMAGES 22
#define COMPUTING_CALIBRATION_PARAMETERS 23
#define MORE_CHESSBOARD_IMAGES_REQUIRED 24
#define WRITING_CALIBRATION_PARAMETERS 25

#define ENTER_KEY 13
#define ESCAPE_KEY 27

namespace usage {
    void prompt(const int& code);
}

#endif //USAGE_H
